/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.65.0
  Forc version: 0.46.1
  Fuel-Core version: 0.20.8
*/

import {
  Account,
  BigNumberish,
  Script,
} from 'fuels';

type ScriptAbiInputs = [];
type ScriptAbiOutput = number;

const _abi = {
  "types": [
    {
      "typeId": 0,
      "type": "u8",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [],
      "name": "main",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
}

const _bin = '0x7400000347000000000000000000002c5dfcc00110fff3001aec5000910000005d43f0002440000047000000000000000000000a'

export class ScriptAbi__factory {

  static readonly abi = _abi
  static readonly bin = _bin

  static createInstance(wallet: Account) {

    const { abi, bin } = ScriptAbi__factory

    const script = new Script<
      ScriptAbiInputs,
      ScriptAbiOutput
    >(bin, abi, wallet);

    return script;

  }

}
