/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  Overrides,
  BigNumberish,
  BytesLike,
  BigNumber,
} from "fuels";

export type ArgsStruct = { receiver: string; amount: BigNumberish };

export type Ret1Struct = { foo: string; bar: string };

export type Ret0Struct = { sender: string; receiver: string; Ret1: Ret1Struct };

interface TokenInterface extends Interface {
  functions: {
    "mint(u64,u64,b256,(b256,u64))": FunctionFragment;
    "send(u64,u64,b256,(b256,b256,u64))": FunctionFragment;
    "get_balance()": FunctionFragment;
    "return_array(u64)": FunctionFragment;
    "return_tuple(u64)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "mint",
    values: [BigNumberish, BigNumberish, string, ArgsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [BigNumberish, BigNumberish, string, ArgsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "get_balance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "return_array",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "return_tuple",
    values: [BigNumberish]
  ): string;

  decodeFunctionData(functionFragment: "mint", data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: "send", data: BytesLike): DecodedValue;
  decodeFunctionData(
    functionFragment: "get_balance",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "return_array",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "return_tuple",
    data: BytesLike
  ): DecodedValue;
}

export class Token extends Contract {
  interface: TokenInterface;
  functions: {
    mint(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: ArgsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "mint(u64,u64,b256,(b256,u64))"(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: ArgsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    send(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: ArgsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    "send(u64,u64,b256,(b256,b256,u64))"(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: ArgsStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    get_balance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "get_balance()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    return_array(
      gas: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<[string, string]>;

    "return_array(u64)"(
      gas: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<[string, string]>;

    return_tuple(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<Ret0Struct>;

    "return_tuple(u64)"(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<Ret0Struct>;
  };

  mint(
    gas: BigNumberish,
    coins: BigNumberish,
    asset_id: string,
    args: ArgsStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BigNumber>;

  "mint(u64,u64,b256,(b256,u64))"(
    gas: BigNumberish,
    coins: BigNumberish,
    asset_id: string,
    args: ArgsStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BigNumber>;

  send(
    gas: BigNumberish,
    coins: BigNumberish,
    asset_id: string,
    args: ArgsStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  "send(u64,u64,b256,(b256,b256,u64))"(
    gas: BigNumberish,
    coins: BigNumberish,
    asset_id: string,
    args: ArgsStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  get_balance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BigNumber>;

  "get_balance()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BigNumber>;

  return_array(
    gas: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<[string, string]>;

  "return_array(u64)"(
    gas: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<[string, string]>;

  return_tuple(
    arg0: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Ret0Struct>;

  "return_tuple(u64)"(
    arg0: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Ret0Struct>;
}
