/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  ContractCall,
  ContractCallOptions,
  Overrides,
  BigNumberish,
  BytesLike,
  CallResult,
  ScriptTransactionRequest,
  TransactionResult,
} from "fuels";

export type Ret0Input = {
  foobar: string;
  barfoo: string;
  addresses: [string, string];
};

export type Ret0Output = {
  foobar: string;
  barfoo: string;
  addresses: [string, string];
};

interface TokenInterface extends Interface {
  functions: {
    mint: FunctionFragment;
    send: FunctionFragment;
    get_balance: FunctionFragment;
    return_array: FunctionFragment;
    return_struct: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "mint",
    values: [BigNumberish, BigNumberish, string, [string, BigNumberish]]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "send",
    values: [BigNumberish, BigNumberish, string, [string, string, BigNumberish]]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "get_balance",
    values?: undefined
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "return_array",
    values: [BigNumberish]
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "return_struct",
    values: [BigNumberish]
  ): Uint8Array;

  decodeFunctionData(functionFragment: "mint", data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: "send", data: BytesLike): DecodedValue;
  decodeFunctionData(
    functionFragment: "get_balance",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "return_array",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "return_struct",
    data: BytesLike
  ): DecodedValue;
}

export class Token extends Contract {
  interface: TokenInterface;
  prepareCall: {
    mint(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, BigNumberish],
      options?: ContractCallOptions
    ): ContractCall;

    send(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, string, BigNumberish],
      options?: ContractCallOptions
    ): ContractCall;

    get_balance(options?: ContractCallOptions): ContractCall;

    return_array(
      gas: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;

    return_struct(
      arg0: BigNumberish,
      options?: ContractCallOptions
    ): ContractCall;
  };
  submit: {
    mint(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<bigint>;

    send(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, string, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    get_balance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<bigint>;

    return_array(
      gas: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<[string, string]>;

    return_struct(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<Ret0Output>;
  };
  submitResult: {
    mint(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    send(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, string, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    get_balance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    return_array(
      gas: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;

    return_struct(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<TransactionResult<any>>;
  };
  dryRun: {
    mint(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<bigint>;

    send(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, string, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    get_balance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<bigint>;

    return_array(
      gas: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<[string, string]>;

    return_struct(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<Ret0Output>;
  };
  dryRunResult: {
    mint(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    send(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, string, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    get_balance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    return_array(
      gas: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    return_struct(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;
  };
  simulate: {
    mint(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<bigint>;

    send(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, string, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    get_balance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<bigint>;

    return_array(
      gas: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<[string, string]>;

    return_struct(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<Ret0Output>;
  };
  simulateResult: {
    mint(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    send(
      gas: BigNumberish,
      coins: BigNumberish,
      asset_id: string,
      args: [string, string, BigNumberish],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    get_balance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    return_array(
      gas: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;

    return_struct(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<CallResult>;
  };

  mint(
    gas: BigNumberish,
    coins: BigNumberish,
    asset_id: string,
    args: [string, BigNumberish],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<bigint>;

  send(
    gas: BigNumberish,
    coins: BigNumberish,
    asset_id: string,
    args: [string, string, BigNumberish],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  get_balance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<bigint>;

  return_array(
    gas: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<[string, string]>;

  return_struct(
    arg0: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Ret0Output>;
}
