/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.62.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.6
*/

import { Interface, Contract, ContractFactory } from "fuels";
import type { Provider, Account, AbstractAddress, BytesLike, DeployContractOptions } from "fuels";
import type { SampleAbi, SampleAbiInterface } from "../SampleAbi";

const _abi = {
  "types": [
    {
      "typeId": 0,
      "type": "u64",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "input",
          "type": 0,
          "typeArguments": null
        }
      ],
      "name": "return_input",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
}

export class SampleAbi__factory {
  static readonly abi = _abi
  static createInterface(): SampleAbiInterface {
    return new Interface(_abi) as unknown as SampleAbiInterface
  }
  static connect(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider
  ): SampleAbi {
    return new Contract(id, _abi, accountOrProvider) as unknown as SampleAbi
  }
  static async deployContract(
    bytecode: BytesLike,
    wallet: Account,
    options: DeployContractOptions = {}
  ): Promise<SampleAbi> {
    const factory = new ContractFactory(bytecode, _abi, wallet);
    const contract = await factory.deployContract(options);
    return contract as unknown as SampleAbi;
  }
}
