version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    commit-message:
      prefix: "build(deps):"
    versioning-strategy: "increase"
    groups:
      deps-major:
        applies-to: "version-updates"
        update-types:
          - "major"
      deps-minor:
        applies-to: "version-updates"
        update-types:
          - "patch"
      deps-patch:
        applies-to: "version-updates"
        update-types:
          - "patch"
    ignore:
      # As of v6.0, ora is ESM only
      # https://github.com/sindresorhus/ora/releases/tag/v6.0.0
      # Blocked by: https://github.com/FuelLabs/fuels-ts/issues/3447
      - dependency-name: "ora"
        update-types:
          - "version-update:semver-major"

      # https://github.com/FuelLabs/fuels-ts/issues/2666
      - dependency-name: "tsup"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

      # https://github.com/FuelLabs/fuels-ts/issues/3724
      - dependency-name: "eslint"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@typescript-eslint/eslint-plugin"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@typescript-eslint/parser"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    commit-message:
      prefix: "ci(deps):"
