version: v1

labels:
  - label: "feat"
    matcher:
      title: "^feat:"
  - label: "bug"
    matcher:
      title: "^fix:"
  - label: "chore"
    matcher:
      title: "^(chore|build|ci):"
  - label: "docs"
    matcher:
      title: "^docs:"
