/* Autogenerated file. Do not edit manually. */

/* eslint-disable @typescript-eslint/no-useless-constructor */
/* eslint-disable @typescript-eslint/no-shadow */
/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.101.3
*/

export { Src14OwnedProxy } from './Src14OwnedProxy';
export { Src14OwnedProxyFactory } from './Src14OwnedProxyFactory';
