/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Interface } from "@fuel-ts/abi-coder";
import type { Provider } from "@fuel-ts/providers";
import { Contract } from "@fuel-ts/contract";
import type { Token, TokenInterface } from "../Token";
const _abi = [
  {
    inputs: [
      {
        name: "gas",
        type: "u64",
      },
      {
        name: "coins",
        type: "u64",
      },
      {
        name: "color",
        type: "b256",
      },
      {
        name: "args",
        type: "tuple",
        components: [
          {
            name: "reciever",
            type: "b256",
          },
          {
            name: "amount",
            type: "u64",
          },
        ],
      },
    ],
    name: "mint",
    outputs: [],
    type: "function",
  },
  {
    inputs: [
      {
        name: "gas",
        type: "u64",
      },
      {
        name: "coins",
        type: "u64",
      },
      {
        name: "color",
        type: "b256",
      },
      {
        name: "args",
        type: "tuple",
        components: [
          {
            name: "sender",
            type: "b256",
          },
          {
            name: "reciever",
            type: "b256",
          },
          {
            name: "amount",
            type: "u64",
          },
        ],
      },
    ],
    name: "send",
    outputs: [],
    type: "function",
  },
];

export class Token__factory {
  static readonly abi = _abi;
  static createInterface(): TokenInterface {
    return new Interface(_abi as any) as TokenInterface;
  }
  static connect(address: string, signerOrProvider: Provider): Token {
    return new Contract(address, _abi, signerOrProvider) as Token;
  }
}
