/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet } from "fuels";
import { Interface, Contract } from "fuels";
import type { Token, TokenInterface } from "../Token";
const _abi = [
  {
    inputs: [
      {
        name: "gas",
        type: "u64",
      },
      {
        name: "coins",
        type: "u64",
      },
      {
        name: "asset_id",
        type: "b256",
      },
      {
        name: "args",
        type: "(b256,u64)",
        components: [
          {
            name: "__tuple_element",
            type: "b256",
          },
          {
            name: "__tuple_element",
            type: "u64",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "",
        type: "u64",
        components: null,
      },
    ],
    name: "mint",
    type: "function",
  },
  {
    inputs: [
      {
        name: "gas",
        type: "u64",
      },
      {
        name: "coins",
        type: "u64",
      },
      {
        name: "asset_id",
        type: "b256",
      },
      {
        name: "args",
        type: "(b256,b256,u64)",
        components: [
          {
            name: "__tuple_element",
            type: "b256",
          },
          {
            name: "__tuple_element",
            type: "b256",
          },
          {
            name: "__tuple_element",
            type: "u64",
          },
        ],
      },
    ],
    name: "send",
    type: "function",
  },
  {
    name: "get_balance",
    type: "function",
    outputs: [
      {
        name: "",
        type: "u64",
        components: null,
      },
    ],
  },
  {
    inputs: [
      {
        name: "gas",
        type: "u64",
      },
    ],
    name: "return_array",
    outputs: [
      {
        name: "__array_element",
        type: "[b256; 2]",
        components: null,
      },
    ],
    type: "function",
  },
  {
    name: "return_struct",
    type: "function",
    inputs: [
      {
        name: "arg0",
        type: "u64",
      },
    ],
    outputs: [
      {
        type: "struct Ret0",
        name: "Ret0",
        components: [
          {
            name: "foobar",
            type: "b256",
          },
          {
            name: "barfoo",
            type: "b256",
          },
          {
            type: "(b256, b256)",
            name: "addresses",
            components: [
              {
                name: "__tuple_element",
                type: "b256",
              },
              {
                name: "__tuple_element",
                type: "b256",
              },
            ],
          },
        ],
      },
    ],
  },
];

export class Token__factory {
  static readonly abi = _abi;
  static createInterface(): TokenInterface {
    return new Interface(_abi) as TokenInterface;
  }
  static connect(id: string, walletOrProvider: Wallet | Provider): Token {
    return new Contract(id, _abi, walletOrProvider) as Token;
  }
}
