name: Lint & Test
on:
  workflow_call:

jobs:
  setup-pnmp:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ESLint and Build
        run: |
          BUILD_VERSION="0.0.0-${{ github.ref_name }}-$(git rev-parse --short $GITHUB_SHA)" pnpm build
          pnpm lint

      - name: Setup Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Test Coverage
        run: pnpm ci:test-coverage
