version: "3"

services:
  fuel-core:
    build: ./services/fuel-core
    # image: ghcr.io/fuellabs/fuel-core:v0.6.3
    ports:
      - "4000:4000"
    volumes:
      - fuel-core-db:/mnt/db
volumes:
  fuel-core-db:
