./Forc.toml
./apps/demo-typegen/contract/Forc.toml
./apps/docs-snippets/projects/echo-values/Forc.toml
./apps/docs-snippets/projects/echo-evm-address/Forc.toml
./apps/docs-snippets/projects/Forc.toml
./apps/docs-snippets/projects/sum-option-u8/Forc.toml
./apps/docs-snippets/projects/echo-employee-data-vector/Forc.toml
./apps/docs-snippets/projects/log-values/Forc.toml
./apps/docs-snippets/projects/counter/Forc.toml
./apps/docs-snippets/projects/echo-enum/Forc.toml
./apps/docs-snippets/projects/token-depositor/Forc.toml
./apps/docs-snippets/projects/simple-predicate/Forc.toml
./apps/docs-snippets/projects/employee-data/Forc.toml
./apps/docs-snippets/projects/echo-u64-array/Forc.toml
./apps/docs-snippets/projects/whitelisted-address-predicate/Forc.toml
./apps/docs-snippets/projects/echo-configurables/Forc.toml
./apps/docs-snippets/projects/simple-token-abi/Forc.toml
./apps/docs-snippets/projects/return-context/Forc.toml
./apps/docs-snippets/projects/script-transfer-to-contract/Forc.toml
./apps/docs-snippets/projects/transfer-to-address/Forc.toml
./apps/docs-snippets/projects/simple-token/Forc.toml
./apps/docs-snippets/projects/return-true-predicate/Forc.toml
./apps/docs-snippets/projects/sum-script/Forc.toml
./packages/program/src/multicall/Forc.toml
./packages/abi-coder/test/sway-projects/exhaustive-examples/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/script-with-configurable/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/custom_errors/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/vector-types-contract/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/advanced-logging-other-contract/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/advanced-logging/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/predicate-vector-types/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/script-main-two-args/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/script-with-vector/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/token_contract/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/advanced-logging-other-contract-abi/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/predicate-address/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/call-test-contract/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/liquidity-pool/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/token_abi/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/payable-annotation/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/configurable-contract/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/predicate-main-args-vector/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/script-with-vector-mixed/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/auth_testing_contract/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/collision_in_fn_names/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/script-main-return-struct/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/predicate-true/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/predicate-false/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/generic-types-contract/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/auth_testing_abi/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/predicate-struct/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/script-main-args/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/predicate-triple-sig/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/predicate-u32/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/script-with-vector-advanced/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/storage-test-contract/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/revert-error/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/predicate-multi-args/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/vector-types-script/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/predicate-main-args-struct/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/coverage-contract/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/predicate-with-configurable/Forc.toml
./packages/fuel-gauge/fixtures/forc-projects/script-with-array/Forc.toml
./packages/utils/test/forc-projects/simple/Forc.toml
./packages/script/src/call-test-script/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/fn-void/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/script-with-configurable/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/minimal/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/enum-of-structs/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/array-with-generics/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/struct-nested/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/struct-simple/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/full/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/predicate/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/option-simple/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/enum-of-enums/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/enum-simple-native/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/tuple-simple/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/script/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/enum-simple/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/array-of-enums/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/struct-with-array/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/evm-address/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/minimal-with-configurable/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/predicate-with-configurable/Forc.toml
./packages/abi-typegen/test/fixtures/forc-projects/vector-simple/Forc.toml
