[project]
authors = ["FuelLabs"]
entry = "lib.sw"
license = "Apache-2.0"
name = "employee-data"

[dependencies]
std = { git = "https://github.com/FuelLabs/sway", branch = "upgrade/fuel-core-v0.20.1" }
