name: "CI setup"
inputs:
  node-version:
    description: "Node version"
    default: 18.14.1
  pnpm-version:
    description: "PNPM version"
    default: 8.6.1
runs:
  using: "composite"
  steps:
    - name: Cache PNPM modules
      uses: actions/cache@v3
      with:
        path: ~/.local/share/pnpm/store/v4
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-pnpm-${{ inputs.pnpm-version }}-lock-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Setup PNPM
      uses: pnpm/action-setup@v2.1.0
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: true
