name: "Test Setup"
inputs:
  node-version:
    description: "Node version"
    default: 20.10.0
  pnpm-version:
    description: "PNPM version"
    default: 9.0.5
runs:
  using: "composite"
  steps:
    - name: Cache PNPM modules
      uses: actions/cache@v4
      with:
        path: ~/.local/share/pnpm/store/v4
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-pnpm-${{ inputs.pnpm-version }}-lock-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: true

    - name: Build
      run: pnpm build
      shell: bash
