[workspace]
members = [
  "counter",
  "echo-enum",
  "log-values",
  "sum-script",
  "echo-values",
  "simple-token",
  "sum-option-u8",
  "employee-data",
  "echo-u64-array",
  "return-context",
  "token-depositor",
  "simple-predicate",
  "simple-token-abi",
  "echo-configurables",
  "transfer-to-address",
  "return-true-predicate",
  "echo-employee-data-vector",
  "whitelisted-address-predicate",
  "echo-evm-address",
  "script-transfer-to-contract",
]
