/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/*
  Fuels version: 0.42.0
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export type { ExampleContractAbi } from './ExampleContractAbi';

export { ExampleContractAbi__factory } from './factories/ExampleContractAbi__factory';
