/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.49.1
  Forc version: 0.40.1
  Fuel-Core version: 0.19.1
*/

export type { ExampleContractAbi } from './ExampleContractAbi';

export { ExampleContractAbi__factory } from './factories/ExampleContractAbi__factory';
