name: "Publish PR to NPM"
inputs:
  npm-token:
    description: "NPM token for authenticating to NPM registry"
    required: true

  github-token:
    description: "GitHub token for authenticating to GitHub"
    required: true

  pr-number:
    description: "PR number"
    default: ${{ github.event.pull_request.number }}

outputs:
  published_version:
    description: "Published version of the PR"
    value: ${{ steps.release.outputs.published_version }}

runs:
  using: "composite"
  steps:
    - name: Ensure NPM access
      shell: bash
      run: npm whoami
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}

    - name: Release to @pr-${{ inputs.pr-number }} tag on npm
      id: release
      shell: bash
      run: |
        pnpm changeset:next
        git add .changeset/fuel-labs-ci.md
        pnpm changeset version --snapshot pr-${{ inputs.pr-number }}
        changetsets=$(pnpm changeset publish --tag pr-${{ inputs.pr-number }})
        published_version=$(echo "$changetsets" | grep -oP '@\K([0-9]+\.){2}[0-9]+-pr-${{ inputs.pr-number }}-\d+' | head -1)
        echo "published_version=$published_version" >> $GITHUB_OUTPUT
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
