/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.66.4
  Fuel-Core version: 0.40.0
*/

import {
  Account,
  BigNumberish,
  BN,
  decompressBytecode,
  Script,
} from 'fuels';

export type ReturnScriptInputs = [];
export type ReturnScriptOutput = BN;

const abi = {
  "programType": "script",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [],
      "name": "main",
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA01RsUoDQRB9F0+8SldNIGwMpDDhyoCV3R6XkERFRwxokONSWoZFrFPaWqgp/YQ9sLDMJ+QTUlrkwEY4SXFODjS3zcy+ebPv7Yz8auIeKCA71iRIp5ZIU8gF4QnWHd1GqpYc4WY5L9BybjP3XF7MoJWNhgKkGoE6ZhTG2F5hHHfCBYRWKLtxEeSbD93i3H9X1ImE7nLetseMl7PcK465//EPD67NbnBl9gLf7HOfI9q2KvVKeOjCYu0t5hUqvdZYE9cu62gQ4Fb7kP0RhNdH6DVXmrMwJhnGqhLG4oDfb+Z0k7VuRGs8Ir67OV435+/t359vitQWgk7NJ/+1Sl7N0WdwmDflniF7Fq53qLI4sFXgDa1gMER9ADwDGy8Oz4xnK/05dGvzWH4LyB9gwvgr108SoMOb+AXzLyk8mAEAAA==');

export class ReturnScript extends Script<ReturnScriptInputs, ReturnScriptOutput> {

  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(wallet: Account) {
    super(bytecode, abi, wallet);
  }
}
