/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.66.4
  Fuel-Core version: 0.40.0
*/

import {
  Account,
  BigNumberish,
  decompressBytecode,
  Script,
} from 'fuels';

export type ScriptMainArgsInputs = [foo: BigNumberish];
export type ScriptMainArgsOutput = number;

const abi = {
  "programType": "script",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "str[6]",
      "concreteTypeId": "ed705f920eb2c423c81df912430030def10f03218f0a064bfab81b68de71ae21"
    },
    {
      "type": "u8",
      "concreteTypeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [
        {
          "name": "foo",
          "concreteTypeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
        }
      ],
      "name": "main",
      "output": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b",
      "attributes": null
    }
  ],
  "loggedTypes": [
    {
      "logId": "17109280065296974883",
      "concreteTypeId": "ed705f920eb2c423c81df912430030def10f03218f0a064bfab81b68de71ae21"
    },
    {
      "logId": "14454674236531057292",
      "concreteTypeId": "c89951a24c6ca28c13fd1cfdc646b2b656d69e61a92b91023be7eb58eb914b6b"
    }
  ],
  "messagesTypes": [],
  "configurables": []
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA21Uz2sTQRR+Sbc1qG1GTWGZWlgwLXtcMAVPdpZk2Y1pyMS2NGK3q4jSg9AltD3vsQcPWvDXrfQPkK1U6HEPHjz2T8jFQ6ALuQQSeohvJgldq7nMmzdvv+99732EdgzYBUiD/CmOO4hSZDAAesHhA4DBi6H2sgQ3Ny0CtE1A6z2ExmUrzS9bCn5HqH0OvBIS8UZ/a9ffv4n3pgNEj3NBs4Rn8ZS5FqRcE2DBJPARUoNPGRjxpRr01RFQrwXI26FtuI63RYuIVwJVjxWGNWcyRkxuhyryqLqlBJjflrGZC9zVcNqthTNuMcxi7RSxFDZbzkX7DqQQ7wbWpefKhaC5gm/VfLS4AqDPl4ByH9xKZ4KUtYhvhEGzARl9fSEgZknomdLNNcFz4MXsjhcbd72Y3MMejEQPR+MeuH3CrvIn2OuJnrhnhrP7R+tjoRUxHTm/Iea5jIWuYifl2iF1K+FcIaU8RRyVtoP/4VRHOI0ETiuBk0ac+4gzL3BoN4BDsYe+D19wL59xP096gHuC7NWewKFF3JPdwlkosOhg3vGB10LVi7UJkcNT8S5gUuqMCwF6xMAZq3rlNJKnmY9oF5ALsfpkxAXZEddygmub2si1+h7oBvqiEvImw+/LOZBnnBde0cc+QC2T3ASCdQx3kuGWlkG+DOqOsE6VHjTzTJ51hdEuEz1s0z4f97A86iHpSzLUiz1UsIdaeEbbxl9z3gOwaQ29yUVPS6LmSMa1H8BXkXcN4/oSw3xDxlWLuV54y30e3kZ/TpO6wWbXrWB/TfpyCmvSc+uvGXnG2WJDeHI3ops+kOputFUFodn3Yn/Gi19k0YMEcQ3JV50UbwcyNmUfvUS+h/dW4n4udFz3DGrxpGdq6D2Oc8JanDV6pwC0S4Q/CO1r43lJf+w90t7s7ADEvnc48/3ng19f68crb4/fDf9XJvQ/SWSDYmgEAAA=');

export class ScriptMainArgs extends Script<ScriptMainArgsInputs, ScriptMainArgsOutput> {

  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(wallet: Account) {
    super(bytecode, abi, wallet);
  }
}
