/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.66.4
  Fuel-Core version: 0.40.0
*/

import {
  Account,
  BigNumberish,
  decompressBytecode,
  Script,
} from 'fuels';

export type ScriptSumInputs = [inputted_amount: BigNumberish];
export type ScriptSumOutput = number;

export type ScriptSumConfigurables = Partial<{
  AMOUNT: BigNumberish;
}>;

const abi = {
  "programType": "script",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "u32",
      "concreteTypeId": "d7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [
        {
          "name": "inputted_amount",
          "concreteTypeId": "d7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc"
        }
      ],
      "name": "main",
      "output": "d7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "AMOUNT",
      "concreteTypeId": "d7649d428b9ff33d188ecbf38a7e4d8fd167fa01b2e10fe9a8f9308e52f1d7cc",
      "offset": 952
    }
  ]
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA21Tz2sTQRT+Ni4YKtiNTSROTdxCUvciBEy9dpYkJDFdOiGRBnTZCj14khCk5rh/ggpqj969bMCDxz167J+wBw9Ku5CDhZQe4ptd15Y0c3lvvvner29m2LSCN0AK0brx3Z77ijaf4z2QFidTiJ9QRcChzx5jcBGkxEWgEv81OxXEUd6J3mTwkmNFNL2hE+K2qE2GoxbShpl1pc9+YzH2Lasdg/hj4q8S51XCt2veoyX8r5I/qqvYrAOsPoToeEdOqK1JjGzWOUVuVEfeCEuc8v6gfHmj+c0VnYkx2iG/nfUJz0d+o+RTvJvg9nNPs/e8jN307lCcqrWzbs4q88MdKFT7JvFS61bfH/Xp7NkW3+wDRuGAswH1sesFNMP9EaczqwqtccClbzSqEDVv5oT7D5xQ6E6ob1D9StRXQ5W6aJEvNWpOxlfwMe355d5rXfI8L8FJp7uioWk0xy+qXxCmnqY+pYY+xeyTFpphlnhkuyq3Ta7YXY5yF/gIrH5Kk47R/UFjtS9gTResE5CWhJ94i/rfkvrTmUK54zoN1Wd/gA8y/lzHEeX7THmfzqL820n+OHeAJXf6kHWOl+EbbHcpvs56S/Fc9Db6yBfbZW7vTZUMWdprRWsr3pMttEu+7Lto1X27F2GQWMEsgZ1Rr+daMsP2vxn+a5TMYLeBF20dtkVDWxXumBWK1a/GJvNfj21xipH3NlVyZhWHPH5bjE9Bd5rKmKq7ZkLiKnFS9+gtsbPoXypP6Fcu1mjGn3UlNsCcFhlF+n8Bqz87WtADAAA=');

export class ScriptSum extends Script<ScriptSumInputs, ScriptSumOutput> {

  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(wallet: Account) {
    super(bytecode, abi, wallet);
  }
}
