/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

interface ContractAbiInterface extends Interface {
  functions: {
    counter: FunctionFragment;
    increment: FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "counter",
    values?: undefined
  ): Uint8Array;
  encodeFunctionData(
    functionFragment: "increment",
    values: [BigNumberish]
  ): Uint8Array;

  decodeFunctionData(
    functionFragment: "counter",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "increment",
    data: BytesLike
  ): DecodedValue;
}

export class ContractAbi extends Contract {
  interface: ContractAbiInterface;
  functions: {
    counter: InvokeFunction<[], BN>;

    increment: InvokeFunction<[param: BigNumberish], BN>;
  };
}
