/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type { BarAbi, BarAbiInterface } from "../BarAbi";
const _abi = [
  {
    type: "function",
    name: "bar",
    inputs: [],
    outputs: [
      {
        type: "b256",
        name: "",
      },
    ],
  },
];

export class BarAbi__factory {
  static readonly abi = _abi;
  static createInterface(): BarAbiInterface {
    return new Interface(_abi) as unknown as BarAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): BarAbi {
    return new Contract(id, _abi, walletOrProvider) as unknown as BarAbi;
  }
}
