import { renderHbsTemplate } from './renderHbsTemplate';

describe('renderHbsTemplate.ts', () => {
  test('should render given template w/ data while injecting header', () => {
    const template = `{{header}}\nHello, {{project}}!`;
    const data = { project: 'Fuel' };
    const rendered = renderHbsTemplate({ template, data });

    expect(rendered).toMatch(/Autogenerated file/g);
    expect(rendered).toMatch(/tslint:disable/g);
    expect(rendered).toMatch(/eslint-disable/g);
    expect(rendered).toMatch(/Fuels version: 0.0.0/g);
    expect(rendered).toMatch(/Forc version: 0.0.0/g);
    expect(rendered).toMatch(/Fuel-Core version: 0.0.0/g);

    expect(rendered).toMatch(/Hello, Fuel!/g);
  });
});
