/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.66.4
  Fuel-Core version: 0.40.0
*/

import { Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  AbstractAddress,
  BigNumberish,
  BN,
  Bytes,
  FunctionFragment,
  InvokeFunction,
  StdString,
} from 'fuels';

const abi = {
  "programType": "contract",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "struct std::string::String",
      "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
      "metadataTypeId": 3
    }
  ],
  "metadataTypes": [
    {
      "type": "raw untyped ptr",
      "metadataTypeId": 0
    },
    {
      "type": "struct std::bytes::Bytes",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "buf",
          "typeId": 2
        },
        {
          "name": "len",
          "typeId": 4
        }
      ]
    },
    {
      "type": "struct std::bytes::RawBytes",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "ptr",
          "typeId": 0
        },
        {
          "name": "cap",
          "typeId": 4
        }
      ]
    },
    {
      "type": "struct std::string::String",
      "metadataTypeId": 3,
      "components": [
        {
          "name": "bytes",
          "typeId": 1
        }
      ]
    },
    {
      "type": "u64",
      "metadataTypeId": 4
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "value",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        }
      ],
      "name": "echo_string",
      "output": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c",
      "attributes": null
    },
    {
      "inputs": [
        {
          "name": "value",
          "concreteTypeId": "9a7f1d3e963c10e0a4ea70a8e20a4813d1dc5682e28f74cb102ae50d32f7f98c"
        }
      ],
      "name": "string_comparison",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const storageSlots: StorageSlot[] = [];

export class EchoStdStringInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    echo_string: FunctionFragment;
    string_comparison: FunctionFragment;
  };
}

export class EchoStdString extends Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: EchoStdStringInterface;
  declare functions: {
    echo_string: InvokeFunction<[value: StdString], StdString>;
    string_comparison: InvokeFunction<[value: StdString], boolean>;
  };

  constructor(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
