/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels";
import { Interface, Contract } from "fuels";
import type { ContractAbi, ContractAbiInterface } from "../ContractAbi";
const _abi = [
  {
    type: "function",
    name: "counter",
    inputs: [],
    outputs: [
      {
        type: "u64",
        name: "",
      },
    ],
  },
  {
    type: "function",
    name: "increment",
    inputs: [
      {
        type: "u64",
        name: "param",
      },
    ],
    outputs: [
      {
        type: "u64",
        name: "",
      },
    ],
  },
];

export class ContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): ContractAbiInterface {
    return new Interface(_abi) as unknown as ContractAbiInterface;
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): ContractAbi {
    return new Contract(id, _abi, walletOrProvider) as unknown as ContractAbi;
  }
}
