/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.0.0
  Forc version: 0.0.0
  Fuel-Core version: 0.0.0
*/

export type { ExampleContractAbi } from './ExampleContractAbi';

export { ExampleContractAbi__factory } from './factories/ExampleContractAbi__factory';
