name: 🚀 Feature request
description: Suggest an idea for this project.
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Motivation
      description: Outline the motivation for the proposal.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Usage example
      description: Provide documentation and code examples for how this feature would be used.
  - type: textarea
    attributes:
      label: Possible implementations
      description: If possible, describe how this feature could be implemented.
