/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.62.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.6
*/

export default '0x740000034700000000000000000000445dfcc00110fff3005d4060495d47f000134904407648000272f0007b36f000001aec5000910000005d40604a2440000047000000000000002d8ccb5b'