/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.62.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.6
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

interface SampleAbiInterface extends Interface {
  functions: {
    return_input: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'return_input', values: [BigNumberish]): Uint8Array;

  decodeFunctionData(functionFragment: 'return_input', data: BytesLike): DecodedValue;
}

export class SampleAbi extends Contract {
  interface: SampleAbiInterface;
  functions: {
    return_input: InvokeFunction<[input: BigNumberish], BN>;
  };
}
