import { unlink } from 'fs';
import { join } from 'path';

const docsDir = join(__dirname, '../src/');

/**
 * Array of files to remove from docs. This could be files that would be do not want to be exposed in the docs or indexed,
 * or files that are generated by other scripts/packages.
 */
const filesToRemove = ['api/modules.md'];

const { log } = console;

filesToRemove.forEach((filePath) => {
  const fullFilePath = join(docsDir, filePath);
  unlink(fullFilePath, (err) => {
    if (err) throw err;
    log(`Removed ${fullFilePath}`);
  });
});
