import { readFileSync } from 'fs';
import { ContractFactory, Provider, Script, Wallet, hexlify } from 'fuels';
import { launchTestNode } from 'fuels/test-utils';
import { join } from 'path';

import { SumScript as TypegenScript } from '../../../test/typegen';

/**
 * @group node
 */
describe('Deploying Scripts', () => {
  it('deploys a script via loader and calls', async () => {
    using launched = await launchTestNode();

    const {
      provider: testProvider,
      wallets: [testWallet],
    } = launched;

    const providerUrl = testProvider.url;
    const WALLET_PVT_KEY = hexlify(testWallet.privateKey);

    const factory = new ContractFactory(TypegenScript.bytecode, TypegenScript.abi, testWallet);
    const { waitForResult: waitForDeploy } = await factory.deployAsBlobTxForScript();
    await waitForDeploy();

    const loaderBytecode = hexlify(
      readFileSync(
        join(
          __dirname,
          '../../../test/fixtures/forc-projects/sum-script/out/release/sum-script-loader.bin'
        )
      )
    );

    // #region deploying-scripts
    // #import { Provider, Wallet, hexlify };
    // #context import { readFileSync } from 'fs';
    // #context import { WALLET_PVT_KEY } from 'path/to/my/env/file';
    // #context import { TypegenScript } from 'path/to/typegen/outputs';

    // First, we will need the loader bytecode that is generated by `fuels deploy`
    // #context const loaderBytecode = hexlify(readFileSync('path/to/forc/build/outputs')));

    const provider = await Provider.create(providerUrl);
    const wallet = Wallet.fromPrivateKey(WALLET_PVT_KEY, provider);

    // Then we will instantiate the script using both the scripts bytecode and it's loader bytecode
    const script = new Script(loaderBytecode, TypegenScript.abi, wallet);

    // Now we are free to interact with the script as we would normally, such as overriding the configurables
    const configurable = {
      AMOUNT: 20,
    };
    script.setConfigurableConstants(configurable);

    const { waitForResult } = await script.functions.main(10).call();
    const { value, gasUsed } = await waitForResult();
    // #endregion deploying-scripts

    const scriptWithoutLoader = new Script(TypegenScript.bytecode, TypegenScript.abi, wallet);
    scriptWithoutLoader.setConfigurableConstants(configurable);
    const { waitForResult: waitForAnotherResult } = await script.functions.main(10).call();
    const { value: anotherValue, gasUsed: anotherGasUsed } = await waitForAnotherResult();

    expect(value).toBe(30);
    expect(anotherValue).toBe(30);
    expect(gasUsed.toNumber()).toBeLessThan(anotherGasUsed.toNumber());
  });
});
