[project]
license = "Apache-2.0"
name = "revert-error"

[dependencies]
custom_errors = { path = "../custom_errors" }
std = { git = "https://github.com/FuelLabs/sway", branch = "feature/fuel-core-0.18" }