/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  BytesLike,
  BigNumberish,
  InvokeFunction,
  BN,
} from "fuels";

interface FooAbiInterface extends Interface {
  functions: {
    foo: FunctionFragment;
  };

  encodeFunctionData(functionFragment: "foo", values?: undefined): Uint8Array;

  decodeFunctionData(functionFragment: "foo", data: BytesLike): DecodedValue;
}

export class FooAbi extends Contract {
  interface: FooAbiInterface;
  functions: {
    foo: InvokeFunction<[], BN>;
  };
}
