import type { Abi } from '../abi/Abi';

/*
  Templates
*/
export const FACTORY_TEMPLATE = `/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, BaseWalletLocked, AbstractAddress } from "fuels"
import { Interface, Contract } from "fuels"
import type { {NAME}, {NAME}Interface } from "../{NAME}"
const _abi = {ABI_JSON}

export class {NAME}__factory {
  static readonly abi = _abi
  static createInterface(): {NAME}Interface {
    return new Interface(_abi) as unknown as {NAME}Interface
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: BaseWalletLocked | Provider
  ): {NAME} {
    return new Contract(id, _abi, walletOrProvider) as unknown as {NAME}
  }
}`;

/*
  Render method
*/
export function renderFactoryTemplate(params: { abi: Abi }) {
  const { abi } = params;
  const json = JSON.stringify(abi.rawContents, null, 2);
  return FACTORY_TEMPLATE.replace(/\{NAME\}/g, abi.name).replace('{ABI_JSON}', json);
}
