export const FACTORY_TEMPLATE = `export /* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet, AbstractAddress } from "fuels"
import { Interface, Contract } from "fuels"
import type { {NAME}Abi, {NAME}AbiInterface } from "../{NAME}Abi"
const _abi = {NAME}

export class {NAME}Abi__factory {
  static readonly abi = _abi
  static createInterface(): {NAME}AbiInterface {
    return new Interface(_abi) as unknown as {NAME}AbiInterface
  }
  static connect(
    id: string | AbstractAddress,
    walletOrProvider: Wallet | Provider
  ): {NAME}Abi {
    return new Contract(id, _abi, walletOrProvider) as unknown as {NAME}Abi
  }
}`;
