import type { Abi } from 'src/abi/Abi';

export const INDEX_TEMPLATE = `/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
{DTS_ITEMS}
{FACTORY_ITEMS}`;

export function renderIndexTemplate(params: { abis: Abi[] }) {
  const dtsBuffer: string[] = [];
  const factoriesBuffer: string[] = [];

  params.abis.forEach((abi) => {
    dtsBuffer.push(`export type { ${abi.name} } from './${abi.name}';`);
    factoriesBuffer.push(`export { ${abi.name}__factory } from './factories/${abi.name}__factory'`);
  });

  let buffer = INDEX_TEMPLATE.replace('{DTS_ITEMS}', dtsBuffer.join('\n'));
  buffer = buffer.replace('{FACTORY_ITEMS}', factoriesBuffer.join('\n'));

  return buffer;
}
