import { contractPaths } from '../../test/fixtures';
import { compileSwayToJson } from '../../test/utils/sway/compileSwayToJson';
import { Abi } from '../Abi';
import { getPackageVersion } from '../utils/getPackageVersion';

import { renderIndexTemplate } from '.';

const expectedRenderedTemplate = `/* Autogenerated file. Do not edit manually. */
/* Fuels version: {FUELS_VERSION} */
/* tslint:disable */
/* eslint-disable */
export type { MyContractAbi } from './MyContractAbi';
export { MyContractAbi__factory } from './factories/MyContractAbi__factory'`;

describe('templates/index', () => {
  test('should render index template', () => {
    const contractPath = contractPaths.minimal;
    const { rawContents } = compileSwayToJson({ contractPath });

    const abi = new Abi({
      filepath: './my-contract-abi.json',
      outputDir: 'stdout',
      rawContents,
    });

    const rendered = renderIndexTemplate({ abis: [abi] });
    const { version: fuelsVersion } = getPackageVersion();

    expect(rendered).toEqual(expectedRenderedTemplate.replace('{FUELS_VERSION}', fuelsVersion));
  });
});
