import type { Abi } from '../Abi';

export function renderIndexTemplate(params: { abis: Abi[] }) {
  const dtsBuffer: string[] = [];
  const factoriesBuffer: string[] = [];

  params.abis.forEach((abi) => {
    dtsBuffer.push(`export type { ${abi.name} } from './${abi.name}';`);
    factoriesBuffer.push(`export { ${abi.name}__factory } from './factories/${abi.name}__factory'`);
  });

  const output = `/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
${dtsBuffer.join('\n')}
${factoriesBuffer.join('\n')}`;

  return output;
}
