/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.66.4
  Fuel-Core version: 0.40.0
*/

import {
  BigNumberish,
  BN,
  decompressBytecode,
  InputValue,
  Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type ConfigurablePinConfigurables = Partial<{
    PIN: BigNumberish;
}>;

export type ConfigurablePinInputs = [pin: BigNumberish];

export type ConfigurablePinParameters = Omit<
  PredicateParams<ConfigurablePinInputs, ConfigurablePinConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [
        {
          "name": "pin",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "PIN",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 376
    }
  ]
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA3WQP0oDQRTGvxmjGVBwYK2eRaZIIVYBUbDbZV2yiQamtFlCjuAiwTJXUPBP6RFyhBzBI0xhI1FIoZCQYn27a5Ak5MHwhjff7zfwaNLALSBRlLhLspHQWYZ7QNnxBPadu/Nhpie4njtp567C+UP6tEXmxsdWL5LwWhr9GDtpDOlFB4P+BcQZG3uBbHNecN/rfgE0Hq66DIVvoA++LM+P83ndBx6B/SfFbPmnpvAV1ByALh02OHdzlt+EDYcqvYI6iioj+gYecn5m8MK+Z/a2p4W/tvCXboekBT4GSQdILZTunKIbNEA/BjTTC772x1fX+NiHF9Q5z/P/fDXPN8tlc22f/wJoWXbDgAEAAA==');

export class ConfigurablePin extends Predicate<
  ConfigurablePinInputs,
  ConfigurablePinConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: ConfigurablePinParameters) {
    super({ abi, bytecode, ...params });
  }
}
