/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.66.4
  Fuel-Core version: 0.40.0
*/

import {
  BigNumberish,
  BN,
  decompressBytecode,
  InputValue,
  Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type ValidationInput = { has_account: boolean, total_complete: BigNumberish };
export type ValidationOutput = { has_account: boolean, total_complete: BN };

export type PredicateMainArgsStructConfigurables = undefined;

export type PredicateMainArgsStructInputs = [received: ValidationInput];

export type PredicateMainArgsStructParameters = Omit<
  PredicateParams<PredicateMainArgsStructInputs, PredicateMainArgsStructConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "struct Validation",
      "concreteTypeId": "c7cf8c2be429c961ccb5c32a2951a58f1bb2a4f748ffac2206d4d1761082beaa",
      "metadataTypeId": 0
    }
  ],
  "metadataTypes": [
    {
      "type": "struct Validation",
      "metadataTypeId": 0,
      "components": [
        {
          "name": "has_account",
          "typeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
        },
        {
          "name": "total_complete",
          "typeId": 1
        }
      ]
    },
    {
      "type": "u64",
      "metadataTypeId": 1
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "received",
          "concreteTypeId": "c7cf8c2be429c961ccb5c32a2951a58f1bb2a4f748ffac2206d4d1761082beaa"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const bytecode = decompressBytecode('H4sIAAAAAAAAAyWOParCUBBGz43hvVe84sK1miqFCxAE6xs0aMTC0sIoghtQxNotWPhTugSX4BJcQnoVbATFIo44zRRzzjef3KrMIeA7eVYcjS0K5NJjBXbqKY2TAJdaFm1+Zm0Cl5SXiyamroLeOuob3f+D2GIT610K0uXDhy7GS1dd/+UzZYbXKqMrRs4HokeN/isPeq88/PSQxomKhzX8bv40R3tIY4+0cgaa69LIa65RtpTFGO0zcWm4lHuEPC07dbbqdh7Q0n9v9kMxY+AAAAA=');

export class PredicateMainArgsStruct extends Predicate<
  PredicateMainArgsStructInputs,
  PredicateMainArgsStructConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: PredicateMainArgsStructParameters) {
    super({ abi, bytecode, ...params });
  }
}
