/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.66.4
  Fuel-Core version: 0.40.0
*/

import {
  BigNumberish,
  BN,
  decompressBytecode,
  InputValue,
  Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type PredicateMultiArgsConfigurables = undefined;

export type PredicateMultiArgsInputs = [arg1: BigNumberish, arg2: BigNumberish];

export type PredicateMultiArgsParameters = Omit<
  PredicateParams<PredicateMultiArgsInputs, PredicateMultiArgsConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [
        {
          "name": "arg1",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "arg2",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA5P6YMBQwsDAxAAGjBKx/w8wCvz/zyD1JoBhIgMDR6EDA3OiKxODsKcAQ5kHA1uRBwOTsKtIQ5kLA6MZUEeiI5MXUD8jkOaJf8vAIPV6A4PCD2OGiN8PmAJ+P2AByvFLOV/AJs4p5Q4UfwnU81QAXU4IpEfFgYFhKgOD/DQOoBqge6ScFzBIuT9giPVkAGIFhlhfBoaiAAYOAV9ThnhHAwaprwoMUj8FGGYA1U8H6vP6AdbPjqp/AoOU9wMGYUcWB2FHoPhXIP6pANPDDtLjDvQXAKXjgr8YAQAA');

export class PredicateMultiArgs extends Predicate<
  PredicateMultiArgsInputs,
  PredicateMultiArgsConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: PredicateMultiArgsParameters) {
    super({ abi, bytecode, ...params });
  }
}
