/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.66.4
  Fuel-Core version: 0.40.0
*/

import {
  decompressBytecode,
  InputValue,
  Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type ReturnTruePredicateConfigurables = undefined;

export type ReturnTruePredicateInputs = [];

export type ReturnTruePredicateParameters = Omit<
  PredicateParams<ReturnTruePredicateInputs, ReturnTruePredicateConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA5P6YMBQwsDAxAABEbH/DzAK/P/PIPUmgEHhhzFDxO8HTAG/H7CA1Eg5X2BQcWBgmMrAwDiNgwGsRsr5AYPUFwEGqZ8MDDOAYtOBcl4/GBgAs7XHrVgAAAA=');

export class ReturnTruePredicate extends Predicate<
  ReturnTruePredicateInputs,
  ReturnTruePredicateConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: ReturnTruePredicateParameters) {
    super({ abi, bytecode, ...params });
  }
}
