/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.66.4
  Fuel-Core version: 0.40.0
*/

import {
  decompressBytecode,
  InputValue,
  Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type SimplePredicateConfigurables = undefined;

export type SimplePredicateInputs = [input_address: string];

export type SimplePredicateParameters = Omit<
  PredicateParams<SimplePredicateInputs, SimplePredicateConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "b256",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [
        {
          "name": "input_address",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA5P6YMBQwsDAxAABJ2L/H2AU+P+fQepNAMNEBoaGQgcG5kRXJgZhTwGGMg8GtiIPBiZhV5GGMhcGRjOgBqCcF1A/I5DmKXJgUNB4K8IQ4LwhocgFyHbe4gBkKyCxHWBsqZcMDAo/jBkifj9gCvj9gAXkBinnCwwqDgwMUxkY2KdxMIDdIOW8gEHK/QFDrPcHFgFPhQMLHVkWSH0Fyv0UYJgBVDMdqNbrBwPDH9ZDVv31aUrK5eK8d/a/mhNi+5/30qVdviwVS4JElFdegfpPBgBo8pSR8AAAAA==');

export class SimplePredicate extends Predicate<
  SimplePredicateInputs,
  SimplePredicateConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: SimplePredicateParameters) {
    super({ abi, bytecode, ...params });
  }
}
