/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.66.4
  Fuel-Core version: 0.40.0
*/

import {
  decompressBytecode,
  InputValue,
  Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type WhitelistedAddressPredicateLoaderConfigurables = Partial<{
    WHITELISTED: string;
}>;

export type WhitelistedAddressPredicateLoaderInputs = [address: string];

export type WhitelistedAddressPredicateLoaderParameters = Omit<
  PredicateParams<WhitelistedAddressPredicateLoaderInputs, WhitelistedAddressPredicateLoaderConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "b256",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [
        {
          "name": "address",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "WHITELISTED",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b",
      "offset": 88
    }
  ]
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA5NyMGAIcGQwkHIJYNjlycBg5MDSCOQrxALZQJoDyG9ScBVmCHIVYPFyYWCo/nkpPyDv3TJOHs9UD5XuBxXis3ZXfT/pnLg+N+73Zhl7BghQWM68KcN48tzVR2TtT71fwJd07sXDNW63zR/8ivWZ/5jb0QgAsffBMHgAAAA=');

export class WhitelistedAddressPredicateLoader extends Predicate<
  WhitelistedAddressPredicateLoaderInputs,
  WhitelistedAddressPredicateLoaderConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: WhitelistedAddressPredicateLoaderParameters) {
    super({ abi, bytecode, ...params });
  }
}
