/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
  Forc version: 0.66.4
  Fuel-Core version: 0.40.0
*/

import {
  decompressBytecode,
  InputValue,
  Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type WhitelistedAddressPredicateConfigurables = Partial<{
    WHITELISTED: string;
}>;

export type WhitelistedAddressPredicateInputs = [address: string];

export type WhitelistedAddressPredicateParameters = Omit<
  PredicateParams<WhitelistedAddressPredicateInputs, WhitelistedAddressPredicateConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "b256",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [
        {
          "name": "address",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "WHITELISTED",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b",
      "offset": 496
    }
  ]
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA3WQP0hCQRzHv+8pIRT5wKaD8AYJtySxoKWTp/k0xRtbxGxy7RHOjo39oT9LZFNDDRK2OzQ1RHvLRQVFSQ4JmoPdPTNM6Jb7cny/38/vd6QZwiagwzlaM9era0avhx2A8rcm+JO8BQNth7HaFTrvCrf0z5B3rjxbGwyuQlyHL2mgZGHMtqD74lPlUgzavGwsRPWU9Gvynsg3YHCzWuaJKiOvAHk2RntniXkHOwYabLiZ9FJHmzWl1wZaZUdyiyoXYMA+4D3wyO7+fEViVkBWyiBZAcn3yB4m+fQfvneEbw3x+zrpZuQT2FXdnRCOJOtQ5lJth+0fYjOHndiWfIFcBrC56o2AZ+VeSmevft+NTAT5aAi2/OpgogbSMhSDkQ4dMPw/jOH9aJ8hwC0GO636A/VTs0ZJy5mRko7xZ8Yz12UxvHd8fj29dPNRmVy/fXm4WL5fEF+59MnjeHTuGyJxnDIQAgAA');

export class WhitelistedAddressPredicate extends Predicate<
  WhitelistedAddressPredicateInputs,
  WhitelistedAddressPredicateConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: WhitelistedAddressPredicateParameters) {
    super({ abi, bytecode, ...params });
  }
}
