/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.2
  Forc version: 0.60.0
  Fuel-Core version: 0.28.0
*/

export { TestScriptAbi__factory } from './factories/TestScriptAbi__factory';
