version: "3"

services:
  fuel-core:
    platform: linux/amd64
    build: ./services/fuel-core
    ports:
      - "4000:4000"
    environment:
      # This is the private key of the consensus.PoA.signing_key in the chainConfig.json
      # this key is responsible for validating the transactions
      - CONSENSUS_KEY=0xa449b1ffee0e2205fa924c6740cc48b3b473aa28587df6dab12abc245d1f5298
    volumes:
      - fuel-core-db:/mnt/db

volumes:
  fuel-core-db:
