/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.2
  Forc version: 0.60.0
  Fuel-Core version: 0.28.0
*/

export type { TestContractAbi } from './TestContractAbi';

export { TestContractAbi__factory } from './factories/TestContractAbi__factory';
