/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.2
  Forc version: 0.60.0
  Fuel-Core version: 0.28.0
*/

import {
  Account,
  BigNumberish,
  BN,
  Script,
} from 'fuels';

type TestScriptAbiInputs = [input: BigNumberish];
type TestScriptAbiOutput = BN;

const _abi = {
  "encoding": "1",
  "types": [
    {
      "typeId": 0,
      "type": "u64",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "input",
          "type": 0,
          "typeArguments": null
        }
      ],
      "name": "main",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
}

const _bin = '0x1af030007400000200000000000002405dffc00110ffff001aec5000910001d85053b0e86140000a5fed00345043b1a07244000828ed04405fec00015047b0f8724000102847b400504bb17072400010284914005043b1705d47b01f5d4bb0201b481480104514805fed10355d47f0005fed10375d47b02f5d4bb037104514805fed1033760000155d47b03713451040764400095d47b0355d4510005fed103a5047b1985041000872480008284114805d43b03a740000085d47b0355c4510005fed10395047b1985041000872480008284114805d43b039740000075d47b0355fed10385047b1985041000872480008284114805d43b0385047b0105fed00025043b10872480008284114805047b11072480008284504805043b16872480008284114805d43b02d5fed00365047b1b05d43f001264000001a407000504bb0305fed00065d43f0015fed00075fec00085043b060724c0018284124c0504bb118724c0018284904c05043b0b8724c0018284124c0504bb018724c0018284904c05d4fb003505520085d4bb0051059348072400008285914005d43f000104124005047b0785fed300f50491008724c0008284954c05fed00115043b0a072480018284114805047b13072480018284504805043b18072480018284114805043b1805047b0d072480018284504805043b04872480018284114805d47b00950410010504bb0905fed101250452008724c0008284504c05043b14872440010284124405047b158724800102845048072400010285114005d4140015d5140002551000000000000000000080000000000000400'

export const TestScriptAbi__factory = {

  abi: _abi,
  bin: _bin,

  createInstance(wallet: Account) {

    const script = new Script<
      TestScriptAbiInputs,
      TestScriptAbiOutput
    >(_bin, _abi, wallet);

    return script;

  }

}
