/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CoverageContractAbi } from "./CoverageContractAbi";

export { CoverageContractAbi__factory } from "./factories/CoverageContractAbi__factory";
