/*
  This file was generated by the Fuels CLI and manually modified for internal use.

  The source of this contract is located at:
  https://github.com/FuelLabs/sway-standard-implementations/tree/master/src14/owned_proxy

  The versions used to generate this file are:

  Fuels version: 0.94.6
  Forc version: 0.63.5
  Fuel-Core version: 0.35.0
*/

export { Src14OwnedProxy } from './Src14OwnedProxy';
export { Src14OwnedProxyFactory } from './Src14OwnedProxyFactory';
