/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.2
  Forc version: 0.60.0
  Fuel-Core version: 0.28.0
*/

export type { TestPredicateAbiInputs } from './factories/TestPredicateAbi__factory';

export { TestPredicateAbi__factory } from './factories/TestPredicateAbi__factory';
