/* Autogenerated file. Do not edit manually. */

/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */

/*
  Fuels version: 0.97.2
  Forc version: 0.66.5
*/

export * from './Src14OwnedProxy';
export * from './Src14OwnedProxyFactory';
