/* Autogenerated file. Do not edit manually. */

/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */

/*
  Fuels version: 0.98.0
  Forc version: 0.66.5
*/

export { Src14OwnedProxy } from './Src14OwnedProxy';
export { Src14OwnedProxyFactory } from './Src14OwnedProxyFactory';
