/* Autogenerated file. Do not edit manually. */

/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */

/*
  Fuels version: 0.97.2
  Forc version: 0.66.5
*/

import { Src14OwnedProxy } from './Src14OwnedProxy';
import { bytecode } from './Src14OwnedProxy-bytecode';
import { abi } from './Src14OwnedProxy-abi';

import { ContractFactory, type DeployContractOptions } from '@fuel-ts/contract';
import { type Account, type Provider } from '@fuel-ts/account';
import { storageSlots } from './Src14OwnedProxy-storage-slots';

export class Src14OwnedProxyFactory extends ContractFactory<Src14OwnedProxy> {
  static readonly bytecode = bytecode;
  static readonly storageSlots = storageSlots;

  constructor(accountOrProvider: Account | Provider) {
    super(bytecode, abi, accountOrProvider, Src14OwnedProxyFactory.storageSlots);
  }

  static deploy(wallet: Account, options: DeployContractOptions = {}) {
    const factory = new Src14OwnedProxyFactory(wallet);
    return factory.deploy(options);
  }
}
