/* Autogenerated file. Do not edit manually. */

/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */

/*
  Fuels version: 0.97.2
  Forc version: 0.66.5
*/

import type { Src14OwnedProxyTypes as Types } from './Src14OwnedProxyTypes';
import type { InterfaceFunctionMapper, ProgramFunctionMapper } from '../common';

import { Contract } from '@fuel-ts/program';
import { Interface } from '@fuel-ts/abi-coder';
import { type AbstractAddress } from '@fuel-ts/interfaces';
import { type Account, type Provider } from '@fuel-ts/account';
import { abi } from './Src14OwnedProxy-abi';

export * from './Src14OwnedProxyTypes';

export type Src14OwnedProxyConfigurables = Types['configurables'];

export class Src14OwnedProxyInterface extends Interface {
  declare functions: InterfaceFunctionMapper<Types['functions']>;

  constructor() {
    super(abi);
  }
}

export class Src14OwnedProxy extends Contract {
  declare interface: Src14OwnedProxyInterface;
  declare functions: ProgramFunctionMapper<Types['functions']>;

  public static readonly abi = abi;

  constructor(id: string | AbstractAddress, accountOrProvider: Account | Provider) {
    super(id, abi, accountOrProvider);
  }
}
