export enum AbiTypegenProjectsEnum {
  ARRAY_OF_ENUMS = 'array-of-enums',
  ARRAY_WITH_GENERICS = 'array-with-generics',
  BYTES = 'bytes',
  ENUM_OF_ENUMS = 'enum-of-enums',
  ENUM_OF_STRUCTS = 'enum-of-structs',
  ENUM_SIMPLE = 'enum-simple',
  ENUM_SIMPLE_NATIVE = 'enum-simple-native',
  EVM_ADDRESS = 'evm-address',
  FN_VOID = 'fn-void',
  FULL = 'full',
  MINIMAL = 'minimal',
  MINIMAL_WITH_CONFIGURABLE = 'minimal-with-configurable',
  OPTION_SIMPLE = 'option-simple',
  PREDICATE = 'predicate',
  PREDICATE_WITH_CONFIGURABLE = 'predicate-with-configurable',
  RAW_SLICE = 'raw-slice',
  SCRIPT = 'script',
  SCRIPT_WITH_CONFIGURABLE = 'script-with-configurable',
  STD_STRING = 'std-string',
  STRUCT_NESTED = 'struct-nested',
  STRUCT_SIMPLE = 'struct-simple',
  STRUCT_WITH_ARRAY = 'struct-with-array',
  TUPLE_SIMPLE = 'tuple-simple',
  VECTOR_SIMPLE = 'vector-simple',
}

export enum DocSnippetProjectsEnum {
  COUNTER = 'counter',
  ECHO_ENUM = 'echo-enum',
  LOG_VALUES = 'log-values',
  SUM_SCRIPT = 'sum-script',
  ECHO_VALUES = 'echo-values',
  SIMPLE_TOKEN = 'simple-token',
  SUM_OPTION_U8 = 'sum-option-u8',
  ECHO_U64_ARRAY = 'echo-u64-array',
  RETURN_CONTEXT = 'return-context',
  TOKEN_DEPOSITOR = 'token-depositor',
  SIMPLE_PREDICATE = 'simple-predicate',
  ECHO_CONFIGURABLES = 'echo-configurables',
  TRANSFER_TO_ADDRESS = 'transfer-to-address',
  RETURN_TRUE_PREDICATE = 'return-true-predicate',
  ECHO_EMPLOYEE_DATA_VECTOR = 'echo-employee-data-vector',
  WHITELISTED_ADDRESS_PREDICATE = 'whitelisted-address-predicate',
  ECHO_EVM_ADDRESS = 'echo-evm-address',
  ECHO_BYTES = 'echo-bytes',
  ECHO_RAW_SLICE = 'echo-raw-slice',
  ECHO_STD_STRING = 'echo-std-string',
  SCRIPT_TRANSFER_TO_CONTRACT = 'script-transfer-to-contract',
}
