name: "Bench Devnet"

on:
  # Remove this before merging, we only want devnet tests on master
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - release/*

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CI Setup
        uses: ./.github/actions/test-setup

      - name: Pretest
        run: pnpm pretest

      - name: Run Node benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: pnpm bench:node
          token: ${{ secrets.CODSPEED_TOKEN }}
        env:
          DEVNET_WALLET_PVT_KEY: ${{ secrets.DEVNET_WALLET_PVT_KEY }}
