name: create-fuels e2e tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/test-setup
        with:
          node-version: ${{ matrix.env.version || 20 }}
      - name: Run e2e tests
        run: sh ./scripts/create-fuels-e2e.sh
