name: Dependabot Changeset

on:
  pull_request:
    branches:
      - master

jobs:
  create-changeset:
    name: Create Changeset
    runs-on: ubuntu-latest
    ## Comment out the following line to enable the workflow
    #  github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 8.9.0
          run_install: true

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run dependabot changeset script
        run: pnpm changeset:dependabot

      - name: Commit Changeset
        run: |
          git commit -m "build: update dependency changeset"
