name: Dependabot Changeset

on:
  pull_request:
    branches:
      - master

jobs:
  create-changeset:
    name: Create Changeset
    runs-on: ubuntu-latest
    ## Comment out the following line to enable the workflow
    #  github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FuelLabs/github-actions/setups/node@master
        with:
          node-version: 20.10.0
          pnpm-version: 8.9.0
      - uses: FuelLabs/github-actions/setups/npm@master
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run dependabot changeset script
        run: pnpm changeset:dependabot

      - name: Commit Changeset
        run: |
          git commit -m "build: update dependency changeset"
