name: Docs Preview on PR

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "apps/docs/**"
      - "apps/docs-snippets/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with VitePress
        working-directory: apps/docs
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/docs/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    outputs: 
      page_url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "Documentation preview: ${{ needs.deploy.outputs.page_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
