name: Trigger Dispatch on Release

on:
  release:
    types: [published]

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Send Repository Dispatch
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.TARGET_REPO_TOKEN }}" \
          https://api.github.com/repos/FuelLabs/migrations-and-disclosures/dispatches \
          -d '{"event_type":"update_versions"}'
