name: "Rebuild Docs"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rebuild-docs:
    name: Rebuild Docs
    # if: github.head_ref == 'changeset-release/master'
    if: github.head_ref == 'cm/issue-123'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Build
        run: pnpm build

      - name: Build Docs
        run: pnpm typedoc

      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     add: docs
