name: "Deprecate Old Versions"

on:
  workflow_dispatch:
    inputs:
      deprecate_versions:
        type: boolean
        description: Deprecate versions? Otherwise dry-run mode will be used.
        default: false
      filter_by_package_name:
        type: string
        description: Filter by package name
        default: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deprecate-npm-versions:
    name: Deprecate versions next, pr and rc
    runs-on: buildjet-4vcpu-ubuntu-2204
    environment: npm-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Setup NPM registry
        uses: FuelLabs/github-actions/setups/npm@master
        with:
          npm-token: ${{ secrets.NPM_DEPLOY_TOKEN }}

      - name: Ensure NPM access
        run: npm whoami
        env:
          HOME: ${{ github.workspace }}
          NPM_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}

      - name: Deprecate
        run: pnpm release:deprecate
        env:
          HOME: ${{ github.workspace }}
          NPM_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
          DEPRECATE_VERSIONS: ${{ github.event.inputs.deprecate_versions }}
          FILTER_BY_PACKAGE_NAME: ${{ github.event.inputs.filter_by_package_name }}
