name: Close and mark stale issue

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "Oops, seems like we needed more information for this issue, please comment with more details or this issue will be closed in 7 days."
          close-issue-message: "This issue was closed because it is missing author input."
          stale-issue-label: "stale"
          any-of-labels: "awaiting"
          days-before-issue-stale: 14
          days-before-issue-close: 7
